/// <reference types="vite/client" />

/**
 * Fetch pre-built static JSON data from the public/data/ directory.
 * These files are generated by scripts/fetch-astro-data.mjs and served
 * via GitHub Pages CDN, avoiding redundant API calls across users.
 */
export async function fetchStaticData<T>(filename: string): Promise<T | null> {
  try {
    const base = import.meta.env.BASE_URL ?? '/';
    const url = `${base}data/${filename}`;
    const response = await fetch(url);
    if (!response.ok) return null;
    return (await response.json()) as T;
  } catch {
    return null;
  }
}
